### ISSUE TITLE
Replacing the content of an existing item raises an ODServerException

### ISSUE THREAD

**Issue by viciousviper** [OneDrive/onedrive-explorer-win#13]
An attempt to replace the content of an existing file item via the "Upload/Replace Selected Item..." menu option in OneDrive API Explorer results in an ODServerException:

``` javascript
{
  "error": {
    "code":"",
    "message":"The request entity's media type 'application/octet-stream' is not supported for this resource."
  }
}
```

When I suppress the explicit ContentType declaration in `ODConnection.UploadToUrl()`

``` C#
private async Task<ODItem> UploadToUrl(Stream sourceFileStream, ItemUploadOptions options, long localItemSize, Uri serviceUri)
{
  var request = await CreateHttpRequestAsync(serviceUri, ApiConstants.HttpPut);
  //request.ContentType = ApiConstants.ContentTypeBinary;

  options.ModifyRequest(request);

  ...
```

the ODServerException turns into

``` javascript
{
  "error": {
    "code":"",
    "message":"The request contains an entity body but no Content-Type header. The inferred media type 'application/octet-stream' is not supported for this resource."
  }
}
```

I did not find any details on supported media types or any binary/text encoding requirements for file content uploads in the OneDrive API documentation.

Replacing the entire file via the "Upload/New File In Current Folder" menu entry works, though.

**Comment by rgregg** [comment]
Are you using PutContentsAsync? It looks like there is a bug in that method that wasn't putting to /content but just to the filename. The media type error is because putting directly to the filename expects the input to be JSON (metadata) instead of the stream. I've updated this in the dev branch.

**Comment by viciousviper** [comment]
Yes, I am using PutContentsAsync - and I double-checked the corresponding operation in OneDrive API Explorer which apparently ran into the same bug.
Your fix in the dev branch works just fine.
Thanks for nailing this down.
