### ISSUE TITLE
VS 2013

### ISSUE THREAD

**Issue by shiroychoksey** [OneDrive/onedrive-explorer-win#19]
The project doesn't open in Visual Studio 2013 (which is why I was asking for it to be on nugget)

**Comment by rgregg** [comment]
This project was authored in VS 2013 with update 4 installed. Apparently that prevents it from opening unless you also have Update 4 installed. Can you update your VS 2013 install and see if that resolves the problem?

The SDK in this project is really just sample code. We're working on delivering a full blown, fully featured SDK that will be available on NuGet by the end of June.

**Comment by shiroychoksey** [comment]
That works! Thanks for sharing!! It would be good to put it in a note on the GITHub page!
