### ISSUE TITLE
How to compile and run

### ISSUE THREAD

**Issue by bcsanches** [OneDrive/onedrive-explorer-win#3]
Hello, sorry for opening a issue, could not find another way to contact you.

How do I compile the sample, Visual Studio states:
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB3323: Unable to find manifest signing certificate in the certificate store.

**Comment by bcsanches** [comment]
Never mind, figured out that I can disable signing or create a temporary certificate.

**Comment by rgregg** [comment]
Thanks for opening this issue! I've pushed changes that disable the signing requirements so you don't need to work around it.

**Comment by bcsanches** [comment]
Nice! Thank you!
