### ISSUE TITLE
Class ODSerializationException

### ISSUE THREAD

**Issue by WeidongShen** [OneDrive/onedrive-explorer-win#7]
Class ODSerializationException is missing the initialization of JsonData.

Here is the update:

```
    internal ODSerializationException(string message, string jsonData, Exception innerException = null)
        : base(message, innerException)
    {
        JsonData = jsonData;
    }
```

**Comment by rgregg** [comment]
Thanks @WeidongShen. I've fixed that bug in commit 6095def.

**Comment by WeidongShen** [comment]
It should be "JsonData = jsonData;", not "JsonData = JsonData;"

**Comment by rgregg** [comment]
Doh. Fixed the typo.
