### ISSUE TITLE
Which Call Returns ODUserProfile?

### ISSUE THREAD

**Issue by WeidongShen** [OneDrive/onedrive-explorer-win#9]
Which call returns an object of ODUserProfile? Why class ODUserProfile in its own namespace of "OneDrive.DataType", while no other class is in that namespace? Thanks!

**Comment by rgregg** [comment]
That looks like a remnant of old code that hung around. There aren't any calls that return that type. I'll remove it in the next check-in.

**Comment by WeidongShen** [comment]
Thank you very much for the quick reply.

After a user successfully signs in, the first call is usually to get user profile. If ODUserProfile is old code, what is the right call to get user profile information including the email address?

**Comment by rgregg** [comment]
There isn't a way to do that through the OneDrive API. You can query the user's drive to get basic information like their display name. To get information like their e-mail address, you need to query the user's profile, which is available through Live SDK.

**Comment by WeidongShen** [comment]
Just need some clarification on this: Is querying user profile with e-mail address out of scope for OneDrive API and we should only get that functionality through Live SDK. Or, this will be added into OneDrive API in a future release? Thanks!

**Comment by rgregg** [comment]
That's just a "for now" thing. We'll have a better story for looking up profile information in the future.
